### ISSUE TITLE
Bits of the rewrite not working + causing crashes

### ISSUE THREAD

**Issue by tobias76** [BrassGoggledCoders/FantasyKingdoms#5]
BlockRegistry - Something to do with the barrels I believe.
OreDictionary - It just doesn't like it at all.
LanguageRegistry - Doesn't cause crashes, just doesn't load the lang files.

Two items have no texture and a name of item.null (Believe they are the beers).

**Comment by FreneticScribbler** [comment]
I'm on it

**Comment by tobias76** [comment]
Cheers, also, the two tankards aren't registering even though the drink is.

-----Original Message-----

**Comment by FreneticScribbler** [comment]
So basically you broke everything? >.> :P

**Comment by tobias76** [comment]
Not everything :P the items and potions register! ;)

-----Original Message-----

**Comment by FreneticScribbler** [comment]
I'm going to be fairly blunt, this is a bit of a mess. Could take me a little while

**Comment by tobias76** [comment]
It is fairly rough I'll admit but I'm trying to keep as much out of the main class as possible, however I do believe the fact this is the first run through of the rewrite it is guaranteed to be broken in different places.

**Comment by FreneticScribbler** [comment]
I, uh, where did you learn to java?

**Comment by tobias76** [comment]
Primarily trial and error but I have also used multiple books from my local library :P

**Comment by FreneticScribbler** [comment]
I think I can tell - no offence intended. Lemme finish off rewriting your rewrite, and everything should work...perhaps learn by example from my code once I push it.

**Comment by FreneticScribbler** [comment]
Also, may I suggest that we use my core/lib mod - https://github.com/BrassGoggledCoders/Boilerplate for this mod, and that any features you want in the lib you can contribute to that, instead of making your own coremod?

**Comment by tobias76** [comment]
I think you'll find that I love learning so I will happily take any advice / use your code as an example. I'm happy to use that boilerplate if you think it is beneficial to the progress of the mod :)

**Comment by FreneticScribbler** [comment]
Good to hear! I also love learning :D I think its better to have one centeralised lib mod rather than both Boilerplate and MantisCore. I'll add you as a contributor to Boilerplate.

**Comment by tobias76** [comment]
MantisCore was one of the many unfinished ideas I had so it can easily be removed without too much hassle and thankyou (for adding me as a contributor) :D

**Comment by FreneticScribbler** [comment]
Stick it all in boilerplate :)

**Comment by FreneticScribbler** [comment]
Everything should be functional now
